export enum FieldType {
  TEXT_INPUT = 'INPUT',
  TEXT_AREA = 'TEXTAREA',
  NUMBER = 'INPUT_NUMBER',
  SELECT = 'SELECT',
  RADIO_GROUP = 'RADIO_GROUP',
  CHECKBOX = 'CHECKBOX',
  DATE_PICKER = 'DATE_PICKER',
  SWITCH = 'SWITCH',
  DATE_RANGE = 'DATE_RANGE',
  RATE = 'RATE',
  SLIDER = 'SLIDER',
  FILE_UPLOAD = 'FILE_UPLOAD',

  // Layout Containers
  CARD = 'CARD',
  TABS = 'TABS',
  COLLAPSE = 'COLLAPSE',
  STEPS = 'STEPS',

  // Backward compatibility aliases
  TEXT = 'TEXT_INPUT',
  TEXTAREA = 'TEXT_AREA',
  RADIO = 'RADIO_GROUP',
  DATE = 'DATE_PICKER'
}
